name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Manila
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_introduction_title: no
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: "" # List of comma separated languages to ignore
          plugin_languages_skipped: "" # List of comma separated repositories to skip
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_from: 50
          plugin_habits_days: 7
          plugin_habits_charts: no
